{{- if .Values.rbac.create -}}
{{- if .Values.credentialManager.kubernetes.enabled -}}
{{- range .Values.credentialManager.kubernetes.teams }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "concourse.web.fullname" . }}
  namespace: {{ . }}
  labels:
    app: {{ template "concourse.web.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "concourse.web.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "concourse.web.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end -}}
{{- end -}}
